---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    run: explorer
spec:
  type: NodePort
  selector:
    name: explorer
  ports:
  - protocol: TCP
    targetPort: 8080
    nodePort: 30888
    port: 30888
    name: explorer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: explorer
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: explorer
    spec:
      containers:
        - image: frbrkoala/hyperledger-explorer:latest
          name: explorer
          volumeMounts:
            - name: shared
              mountPath: /shared
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc