---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    run: postgresql
spec:
  type: NodePort
  selector:
    name: postgresql
  ports:
  - protocol: TCP
    targetPort: 5432
    nodePort: 30432
    port: 30432
    name: postgresql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: hppoc
            - name: POSTGRES_DB
              value: fabricexplorer
            - name: POSTGRES_PASSWORD
              value: hppoc231242
          volumeMounts:
            - name: shared
              mountPath: /var/lib/postgresql
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-pvc